source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target :CPAProxyTests do
    platform :ios, '8.0'
    pod 'CPAProxy', :path => '../../CPAProxy.podspec'
    pod 'ProxyKit', '~> 1.1.0'
end